#!/bin/sh

# For most Container users, "apt-get install" only happens during "podman build",
# where starting services doesn't work and often fails in humorous ways. This
# prevents those failures by stopping the services from attempting to start.

exit 0
